#webdriver.driver=chrome
#webdriver.base.url=https://pruebas.fisapay.com.co/#!
#serenity.outputDirectory=target/serenity
#serenity.requirements.dir=src/test/resources/features

# Serenity BDD Configuration

# Base URL of the application under test
webdriver.base.url=https://pruebas.fisapay.com.co/#!

# WebDriver configuration
webdriver.driver=chrome
webdriver.autodownload=true

# Timeout settings
webdriver.timeouts.implicitlywait=10000
webdriver.wait.for.timeout=10000

# Serenity report configuration
serenity.project.name=Demo Plataforma Serenity Project
serenity.outputDirectory=target/site/serenity
serenity.take.screenshots=FOR_EACH_ACTION
serenity.verbose.steps=false
